// <auto-generated />
// Generated from Unicode Character Database
// Data source: https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt
// Binary resource: UnicodeData.bin.gz
// Statistics:
//   - Total characters: 310341
//   - Emoji characters: 1546
//   - Compressed size: 1,028,596 bytes (6.6% of uncompressed)
//   - Max character name length: 88 chars
//
// Specification: https://www.unicode.org/reports/tr44/
// DO NOT MODIFY THIS FILE MANUALLY - regenerate using the Unicode generator tool

namespace Meziantou.Framework;
internal static partial class UnicodeCharacterInfos
{
    private const int MaxCharacterNameLength = 128;
}