// <auto-generated />
#nullable enable

using System.Collections.Concurrent;
using System.Runtime.InteropServices;

namespace Meziantou.Framework.Http;

partial class HstsDomainPolicyCollection
{
    private void LoadPreloadDomains()
    {
        // HSTS preload data source: https://raw.githubusercontent.com/chromium/chromium/d5e6fd51b430fec89732a3976e666011ecffa0a2/net/http/transport_security_state_static.json
        // Commit date: 2026-09-11T21:03:02.0000000+00:00
        CollectionsMarshal.SetCount(_policies, 4);

        var dict1 = new ConcurrentDictionary<string, HstsDomainPolicy>(concurrencyLevel: -1, capacity: 61, comparer: StringComparer.OrdinalIgnoreCase);
        _policies[0] = dict1;
        Load(dict1, 51, "preload_1.bin");

        var dict2 = new ConcurrentDictionary<string, HstsDomainPolicy>(concurrencyLevel: -1, capacity: 86514, comparer: StringComparer.OrdinalIgnoreCase);
        _policies[1] = dict2;
        Load(dict2, 86504, "preload_2.bin");

        var dict3 = new ConcurrentDictionary<string, HstsDomainPolicy>(concurrencyLevel: -1, capacity: 8080, comparer: StringComparer.OrdinalIgnoreCase);
        _policies[2] = dict3;
        Load(dict3, 8070, "preload_3.bin");

        var dict4 = new ConcurrentDictionary<string, HstsDomainPolicy>(concurrencyLevel: -1, capacity: 163, comparer: StringComparer.OrdinalIgnoreCase);
        _policies[3] = dict4;
        Load(dict4, 153, "preload_4.bin");
    }
}